add python array
rain1024/datastructures-algorithms-competitive-programming pull request #56
Opened 2022-12-01 17:22 UTC by quang-ph

2022-12-01 23:56 UTC, rain1024 requested changes
Please fix the style-check error

2022-12-01 23:56 UTC, rain1024 commented on concepts/python/array.md
> +import array as arr
What are different between `array` and `list`?

Can you simply use `list` in this senario?

2022-12-01 23:56 UTC, rain1024 commented on concepts/python/array.md
> +import array as arr
Interesting. https://www.upgrad.com/blog/python-array-vs-list-differences-use-cases/

2022-12-01 23:56 UTC, rain1024 commented on concepts/python/array.md
> +* ▶️ [CS50 2020 - Lecture 2 - Arrays](https://www.youtube.com/watch?v=tI_tIZFyKBw&t=3009s&ab_channel=CS50), CS50
Worthy mention:
https://docs.python.org/3.8/library/array.html
https://www.upgrad.com/blog/python-array-vs-list-differences-use-cases/

Add two items and your style check error would be fixed.

2022-12-03 03:43 UTC, quang-ph commented on concepts/python/array.md
> +import array as arr
I find some information in this article that is not really correct. "This means that storing such details in an immutable data structure such as an array makes much more sense" -> I think an array is a mutable data structure cause we can update its values after initialization

2022-12-03 03:45 UTC, quang-ph commented on concepts/python/array.md
> +* ▶️ [CS50 2020 - Lecture 2 - Arrays](https://www.youtube.com/watch?v=tI_tIZFyKBw&t=3009s&ab_channel=CS50), CS50
Thank you for your recommendation. I added the contents.

2022-12-03 14:04 UTC, rain1024 approved these changes

2022-12-03 14:06 UTC, merged